### ISSUE TITLE
segmentation violation with unprivileged user

### ISSUE THREAD

**Issue by Jellyfrog** [adyxax/bareos-zabbix-check#1]
Hi,

When I run this as an unprivileged user it segfaults.
Running it as root works.
```
$ ./bareos-zabbix-check
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4ded1f]

goroutine 1 [running]:
git.adyxax.org/adyxax/bareos-zabbix-check/pkg/zabbix.checkStateFile(0x0, 0x0)
        /tmp/a/bareos-zabbix-check/pkg/zabbix/statefile.go:25 +0x47f
git.adyxax.org/adyxax/bareos-zabbix-check/pkg/zabbix.processFlags(0x462d9b, 0x948a222b337c12)
        /tmp/a/bareos-zabbix-check/pkg/zabbix/flags.go:18 +0x191
git.adyxax.org/adyxax/bareos-zabbix-check/pkg/zabbix.Main(0x0, 0x0)
        /tmp/a/bareos-zabbix-check/pkg/zabbix/zabbix.go:22 +0x45
main.main()
        /tmp/a/bareos-zabbix-check/cmd/bareos-zabbix-check/main.go:12 +0x26
```

**Comment by adyxax** [comment]
Hi,

Thank you for taking the time to test this software and open an issue.

I must admit I never bothered to test running this as a non root user as these checks run as root at my workplace. It should not be too hard to implement though, I will look into it tomorrow.

**Comment by adyxax** [comment]
Can I ask you on what operating system you tested? What go version? Anything particular about your setup?

I cannot reproduce this error on Gentoo or on ubuntu 20.04 with go 1.16.

**Comment by adyxax** [comment]
Hmmmm reading the code I see that I do not check properly the state file access... does the user you are running the check has read permission to /var/lib/bareos ? Is this path an existing folder or maybe something else ?

**Comment by Jellyfrog** [comment]
Hi,

No the user I tested with had access to neither the folder nor the socket :) 
I didnt except it to work, but a bit unexpected it would segfault tho :)

**Comment by Jellyfrog** [comment]
It was compiled on arch, and binary moved to centos 7.  
Also tried compiling with CGO_ENABLED=0 just to avoid some issues

**Comment by adyxax** [comment]
Ok thanks again for your time on this, I found an easy fix. I tried to be clever while checking for errors when I should have just been straightforward.
